### PR TITLE
Update build tools version

### PR DESCRIPTION
**Pull request by nightscape**
Should also trigger using a new base image containing a more recent Flutter version.

### CODE REVIEW

**Comment by arnemolland** [comment]
Thanks, this haven't seen much love since I last used it so I appreciate the work!

**Comment by nightscape** [comment]
Work is an overstatement 😁 
Thanks for merging!

**Comment by nightscape** [comment]
Just checked on Docker Hub, the new version doesn't show up there.
Did you [set up auto-builds](https://docs.docker.com/docker-hub/builds/), or push manually?
Afair auto-builds are quite simple to set up, but if you don't mind spending the effort, it would be great if you could push a new version!

**Comment by arnemolland** [comment]
I pushed manually for now, will add a workflow for auto-pushing newer versions

**Pull request merged**
